name = "mu4"
description = "The mu4 microkernel OS"
version = "0.1.0-dev"

authors = ["Florian Marrero Liestmann"]
maintainers = ["Florian Marrero Liestmann <f.m.liestmann@fx-ttr.de>"]
maintainers-logins = ["fxttr"]
licenses = "GPL-3.0-or-later"
website = "https://github.com/fxttr/mu4"
tags = []

executables = ["mu4"]
